version: '3'

services:

  logingest:
    image: cisl-repo/xdmod_cisl_logingest:${TAG_logingest}
    volumes:
      - ${VOLMAP_SECRETS}:/run/secrets
      - ${VOLMAP_LOGS}:/var/log
    ports:
      - "${PORTMAP_WEBAPP}:8080"
    networks:
      - default
    env_file:
      - deploy.env
    command: /bin/bash

#    environment:
#      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root-password

volumes:
  secrets:
  logs:
  app_data:
  db_data:

networks:
  default:
  mail:
    external:
      name: mail
