BOX_IMAGE = "centos/7"
MANAGER_COUNT = 1
WORKER_COUNT = 2

Vagrant.configure("2") do |config|
  (1..MANAGER_COUNT).each do |i|
    config.vm.define "manager#{i}" do |manager|
      manager.vm.box = BOX_IMAGE
      manager.vm.hostname = "manager#{i}"
      # swarm00.vm.box_url = BOX_IMAGE

      manager.vm.network :private_network, ip: "192.168.56.10#{i}"

      manager.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--memory", 512]
        v.customize ["modifyvm", :id, "--name", "manager#{i}"]
      end
    end
  end

  (1..WORKER_COUNT).each do |i|
    config.vm.define "worker#{i}" do |worker|
      worker.vm.box = BOX_IMAGE
      worker.vm.hostname = "worker#{i}"
      # worker.vm.box_url = BOX_IMAGE

      worker.vm.network :private_network, ip: "192.168.56.20#{i}"

      worker.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--memory", 512]
        v.customize ["modifyvm", :id, "--name", "worker#{i}"]
      end
    end
  end
end
